---

- hosts: all
  become: true
  tasks:
    - name: apt-key add
      apt_key:
        url: "{{ item.url }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", url: "https://dl-ssl.google.com/linux/linux_signing_key.pub" }

    - name: apt-add-repository
      apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" }

    - name: apt install
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "absent", name: "chromium-browser" }
        - { state: "latest", name: "google-chrome-stable" }

    - name: remove duplicated apt source list
      file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "absent", path: "/etc/apt/sources.list.d/google-chrome.list" }
        - { state: "absent", path: "/etc/apt/sources.list.d/google-chrome.list.save" }
