---

- hosts: all
  become: true
  tasks:
    - name: apt-add-repository
      apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", repo: "ppa:ondrej/php" }

    - name: apt install
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "latest", name: "php-apcu" }
        - { state: "latest", name: "php-apcu-bc" }
        - { state: "latest", name: "php-memcache" }
        - { state: "latest", name: "php-uuid" }
        - { state: "latest", name: "php-xdebug" }
        - { state: "latest", name: "php5.6-bcmath" }
        - { state: "latest", name: "php5.6-bz2" }
        - { state: "latest", name: "php5.6-cli" }
        - { state: "latest", name: "php5.6-curl" }
        - { state: "latest", name: "php5.6-fpm" }
        - { state: "latest", name: "php5.6-gd" }
        - { state: "latest", name: "php5.6-imap" }
        - { state: "latest", name: "php5.6-intl" }
        - { state: "latest", name: "php5.6-json" }
        - { state: "latest", name: "php5.6-ldap" }
        - { state: "latest", name: "php5.6-mbstring" }
        - { state: "latest", name: "php5.6-mysql" }
        - { state: "latest", name: "php5.6-opcache" }
        - { state: "latest", name: "php5.6-pgsql" }
        - { state: "latest", name: "php5.6-snmp" }
        - { state: "latest", name: "php5.6-soap" }
        - { state: "latest", name: "php5.6-sqlite3" }
        - { state: "latest", name: "php5.6-tidy" }
        - { state: "latest", name: "php5.6-xml" }
        - { state: "latest", name: "php5.6-xmlrpc" }
        - { state: "latest", name: "php5.6-zip" }
        - { state: "latest", name: "php7.0-bcmath" }
        - { state: "latest", name: "php7.0-bz2" }
        - { state: "latest", name: "php7.0-cli" }
        - { state: "latest", name: "php7.0-curl" }
        - { state: "latest", name: "php7.0-fpm" }
        - { state: "latest", name: "php7.0-gd" }
        - { state: "latest", name: "php7.0-imap" }
        - { state: "latest", name: "php7.0-intl" }
        - { state: "latest", name: "php7.0-json" }
        - { state: "latest", name: "php7.0-ldap" }
        - { state: "latest", name: "php7.0-mbstring" }
        - { state: "latest", name: "php7.0-mysql" }
        - { state: "latest", name: "php7.0-opcache" }
        - { state: "latest", name: "php7.0-pgsql" }
        - { state: "latest", name: "php7.0-snmp" }
        - { state: "latest", name: "php7.0-soap" }
        - { state: "latest", name: "php7.0-sqlite3" }
        - { state: "latest", name: "php7.0-tidy" }
        - { state: "latest", name: "php7.0-xml" }
        - { state: "latest", name: "php7.0-xmlrpc" }
        - { state: "latest", name: "php7.0-zip" }
        - { state: "latest", name: "php7.1-bcmath" }
        - { state: "latest", name: "php7.1-bz2" }
        - { state: "latest", name: "php7.1-cli" }
        - { state: "latest", name: "php7.1-curl" }
        - { state: "latest", name: "php7.1-fpm" }
        - { state: "latest", name: "php7.1-gd" }
        - { state: "latest", name: "php7.1-imap" }
        - { state: "latest", name: "php7.1-intl" }
        - { state: "latest", name: "php7.1-json" }
        - { state: "latest", name: "php7.1-ldap" }
        - { state: "latest", name: "php7.1-mbstring" }
        - { state: "latest", name: "php7.1-mysql" }
        - { state: "latest", name: "php7.1-opcache" }
        - { state: "latest", name: "php7.1-pgsql" }
        - { state: "latest", name: "php7.1-snmp" }
        - { state: "latest", name: "php7.1-soap" }
        - { state: "latest", name: "php7.1-sqlite3" }
        - { state: "latest", name: "php7.1-tidy" }
        - { state: "latest", name: "php7.1-xml" }
        - { state: "latest", name: "php7.1-xmlrpc" }
        - { state: "latest", name: "php7.1-zip" }
        - { state: "latest", name: "php7.2-bcmath" }
        - { state: "latest", name: "php7.2-bz2" }
        - { state: "latest", name: "php7.2-cli" }
        - { state: "latest", name: "php7.2-curl" }
        - { state: "latest", name: "php7.2-fpm" }
        - { state: "latest", name: "php7.2-gd" }
        - { state: "latest", name: "php7.2-imap" }
        - { state: "latest", name: "php7.2-intl" }
        - { state: "latest", name: "php7.2-json" }
        - { state: "latest", name: "php7.2-ldap" }
        - { state: "latest", name: "php7.2-mbstring" }
        - { state: "latest", name: "php7.2-mysql" }
        - { state: "latest", name: "php7.2-opcache" }
        - { state: "latest", name: "php7.2-pgsql" }
        - { state: "latest", name: "php7.2-snmp" }
        - { state: "latest", name: "php7.2-soap" }
        - { state: "latest", name: "php7.2-sqlite3" }
        - { state: "latest", name: "php7.2-tidy" }
        - { state: "latest", name: "php7.2-xml" }
        - { state: "latest", name: "php7.2-xmlrpc" }
        - { state: "latest", name: "php7.2-zip" }

    - name: phpenmod
      php_module:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", name: "apcu" }
        - { state: "present", name: "apcu_bc" }
        - { state: "present", name: "bcmath" }
        - { state: "present", name: "bz2" }
        - { state: "present", name: "calendar" }
        - { state: "present", name: "ctype" }
        - { state: "present", name: "curl" }
        - { state: "present", name: "dom" }
        - { state: "present", name: "exif" }
        - { state: "present", name: "fileinfo" }
        - { state: "present", name: "ftp" }
        - { state: "present", name: "gd" }
        - { state: "present", name: "gettext" }
        - { state: "present", name: "iconv" }
        - { state: "present", name: "imap" }
        - { state: "present", name: "intl" }
        - { state: "present", name: "json" }
        - { state: "present", name: "ldap" }
        - { state: "present", name: "mbstring" }
        - { state: "present", name: "memcache" }
        - { state: "present", name: "mysqli" }
        - { state: "present", name: "mysqlnd" }
        - { state: "present", name: "opcache" }
        - { state: "present", name: "pdo" }
        - { state: "present", name: "pdo_mysql" }
        - { state: "present", name: "pdo_pgsql" }
        - { state: "present", name: "pdo_sqlite" }
        - { state: "present", name: "phar" }
        - { state: "present", name: "posix" }
        - { state: "present", name: "readline" }
        - { state: "present", name: "shmop" }
        - { state: "present", name: "simplexml" }
        - { state: "present", name: "snmp" }
        - { state: "present", name: "soap" }
        - { state: "present", name: "sockets" }
        - { state: "present", name: "sysvmsg" }
        - { state: "present", name: "sysvsem" }
        - { state: "present", name: "sysvshm" }
        - { state: "present", name: "tidy" }
        - { state: "present", name: "tokenizer" }
        - { state: "present", name: "uuid" }
        - { state: "present", name: "wddx" }
        - { state: "present", name: "xml" }
        - { state: "present", name: "xmlreader" }
        - { state: "present", name: "xmlrpc" }
        - { state: "present", name: "xmlwriter" }
        - { state: "present", name: "xsl" }
        - { state: "present", name: "zip" }

    - name: enable service
      service:
        name: "{{ item.name }}"
        enabled: "{{ item.enabled }}"
      with_items:
        - { name: "php5.6-fpm", enabled: "yes" }
        - { name: "php7.0-fpm", enabled: "yes" }
        - { name: "php7.1-fpm", enabled: "yes" }
        - { name: "php7.2-fpm", enabled: "yes" }

    - name: install composer globally
      shell: |
        curl -sL https://getcomposer.org/download/1.6.1/composer.phar > /usr/local/bin/composer
        chown root:root /usr/local/bin/composer
        chmod 777 /usr/local/bin/composer
      args:
        creates: "/usr/local/bin/composer"

    - name: composer self-update
      shell: |
        composer self-update --no-interaction
      register: composer_self_update_result
      changed_when: "'You are already using composer' not in composer_self_update_result.stderr"

    - name: composer global init
      shell: |
        mkdir -p $COMPOSER_HOME
        composer global init --no-interaction
      register: composer_global_init_result
      changed_when: composer_global_init_result.rc != 0
      environment:
        COMPOSER_HOME: "/usr/local/share/composer"
        COMPOSER_BIN_DIR: "/usr/local/bin"

    - name: composer global require
      shell: |
        composer global {{ item.status }} {{ item.name }} --no-interaction
      with_items:
        - { status: 'require', name: 'hirak/prestissimo:@stable' }
        - { status: 'require', name: 'consolidation/cgr:@stable' }
      register: composer_global_require_result
      changed_when: composer_global_require_result.rc != 0
      environment:
        COMPOSER_HOME: "/usr/local/share/composer"
        COMPOSER_BIN_DIR: "/usr/local/bin"

    - name: cgr require
      shell: |
        cgr require {{ item.name }}
      with_items:
        - { name: "drupal/coder:@stable" }
        - { name: "drupal/console:~1.0" }
        - { name: "drush/drush:~8.0" }
        - { name: "friendsofphp/php-cs-fixer:@stable" }
        - { name: "phpunit/phpunit:~5.7" }
        - { name: "sami/sami:@stable" }
        - { name: "squizlabs/php_codesniffer:@stable" }
      register: cgr_require_result
      changed_when: cgr_require_result.rc != 0
      environment:
        COMPOSER_HOME: "/usr/local/share/composer"
        COMPOSER_BIN_DIR: "/usr/local/bin"
        CGR_BIN_DIR: "/usr/local/bin"

    - name: cgr update
      shell: |
        cgr update
      register: cgr_update_result
      changed_when: "'Package operations:' in cgr_update_result.stderr"
      environment:
        COMPOSER_HOME: "/usr/local/share/composer"
        COMPOSER_BIN_DIR: "/usr/local/bin"
        CGR_BIN_DIR: "/usr/local/bin"
